### ISSUE TITLE
feat: streamline deployments, publishing and CI/CD

### ISSUE THREAD

**Issue by git-anurag-hub** [elixir-cloud-aai/cloud-components#22] opened 2023-05-15 08:20 UTC
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
Following are some steps in the solutions:

- Branch Protection Rules
- #33 
- #34
- Package Publishing (include in CI/CD workflow)
- Deployments for each app (include in CI/CD workflow)
- Storybook (include in CI/CD workflow)

**Describe alternatives you've considered**
NA

**Acknowledgement**

> We thank you for your valuable contribution and would like to acknowledge it
> on our [contributors][contributors] page. To help us with that, we would like
> to kindly request that you help us with this by commenting on this issue with
> a request to the [@all-contributors bot][all-contributors-bot] of the form
> `@all-contributors please add @YOUR_GH_HANDLE for TYPE_1, TYPE_2, ...`, where
> `TYPE_1` etc. refer to [contribution types supported by the All Contributors
> Specification][all-contributors-types], e.g., `idea`.

[all-contributors-bot]: <https://allcontributors.org/docs/en/bot/overview>
[all-contributors-types]: <https://allcontributors.org/docs/en/emoji-key>
[contributors]: ../../CONTRIBUTORS

**Comment by uniqueg** [comment] 2023-05-28 23:07
Closed as duplicate of #34. To be clear, it is rather that #34 is a duplicate of _this_ issue, but now there is more content in that issue, so closing this one :)

**Closed by uniqueg** 2023-05-28 23:07 UTC
Labels: status: new, type: feature
